sonar.projectKey=madhubani-3tier-app

sonar.sources=backend,frontend

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

sonar.exclusions=\
backend/node_modules/**,\
backend/coverage/**,\
backend/tests/**,\
frontend/node_modules/**,\
**/dist/**,\
**/build/**

sonar.coverage.exclusions=\
backend/tests/**,\
backend/coverage/**,\
**/*.test.js,\
**/*.spec.js