
mysql:
  image: mysql:8.0
  database: "madhubani_db"
  user: "madhubani_user"
  port: 3306
  existingSecret: "madhubani-db-secret" # The k8s secret you just created
backend:
  image: santosh051/madhubani-backend:1a14ddabdc4b969a6fa34cd5a87f0942adb8c75d
  port: 3000
  replicas: 2
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
frontend:
  image: santosh051/madhubani-frontend:1a14ddabdc4b969a6fa34cd5a87f0942adb8c75d
  port: 80
  replicas: 2
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
