apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-frontend"
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
        env:
        - name: BACKEND_URL
          value: "http://{{ .Release.Name }}-backend:{{ .Values.backend.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-frontend"
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.frontend.port }}
  selector:
    app: frontend