apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-mysql"
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        ports:
        - containerPort: {{ .Values.mysql.port }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.existingSecret }} # Secures the root password
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database | quote }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.user | quote }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.existingSecret }} # Secures the app user password
              key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-mysql"
spec:
  ports:
  - port: {{ .Values.mysql.port }}
  selector:
    app: mysql