name: Madhubani Three-Tier CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  frontend-ci:
    name: Frontend chal raha hai
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Verify frontend files
        run: |
          test -f frontend/index.html
          test -f frontend/style.css
          test -f frontend/app.js
          test -f frontend/nginx.conf
          test -f frontend/Dockerfile

      - name: Check frontend JavaScript syntax
        run: node --check frontend/app.js

  backend-ci:
    name: Backend chal raha hai
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        run: npm ci

      - name: Check backend JavaScript syntax
        run: node --check server.js
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs:
      - frontend-ci
      - backend-ci
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:   # Downloads your frontend, backend, and configuration files
          fetch-depth: 0

      - name: Run sonarqube scan
        uses: sonarsource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
          
      - name: Check SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  #----------------------------------------------------------------------
  #----------------------------------------------------------------------

  # owasp-dependency-check:
  #   # Name displayed in the GitHub Actions dashboard
  #   name: OWASP Dependency Check

  #   # Run after the SonarQube job succeeds
  #   needs: sonarqube

  #   # Use a GitHub-hosted Linux runner
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       # Download the repository code
  #       uses: actions/checkout@v4

  #     - name: Run OWASP Dependency Check
  #       # Load the encrypted GitHub secret into an environment variable
  #       env:
  #         NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

  #       run: |
  #         # Create the report directory
  #         mkdir -p dependency-check-report

  #         if [ -z "${NVD_API_KEY}" ]; then
  #           echo "ERROR: NVD_API_KEY is empty"
  #           exit 1
  #         else
  #           echo "NVD_API_KEY is loaded successfully"
  #         fi

  #         # Run OWASP Dependency-Check
  #         docker run --rm \
  #           -v "${{ github.workspace }}:/src" \
  #           -v "${{ github.workspace }}/dependency-check-report:/report" \
  #           owasp/dependency-check:latest \
  #           --project "Madhubani-3Tier-App" \
  #           --scan "/src" \
  #           --format HTML \
  #           --out "/report" \
  #           --nvdApiKey "${NVD_API_KEY}" \
  #           --failOnCVSS 11 || true

  #         echo "========================"
  #         echo "Contents of report folder"
  #         echo "========================"

  #         # Display generated report files
  #         ls -lah dependency-check-report

  #     - name: Upload OWASP report
  #       # Upload the report even when the scanning step has problems
  #       if: always()

  #       # Store the report as a GitHub Actions artifact
  #       uses: actions/upload-artifact@v4

  #       with:
  #         # Artifact name visible in GitHub Actions
  #         name: owasp-dependency-check-report

  #         # Folder containing the HTML report
  #         path: dependency-check-report/

  #         # Show a clear error when no report exists
  #         if-no-files-found: error

  #         # Keep the report for 14 days
  #         retention-days: 14

  #------------------------------------------------
  #------------------------------------------------

   docker-build-scan-and-push:
    # Job name shown in the GitHub Actions interface.
      name: Build, Scan and Push Docker Images

    # Run only after the SonarQube job succeeds.
      needs: sonarqube

    # Use a GitHub-hosted Ubuntu runner.
      runs-on: ubuntu-latest

      steps:
      # ------------------------------------------------------
      # 1. DOWNLOAD REPOSITORY
      # ------------------------------------------------------
      - name: Checkout source code
        uses: actions/checkout@v4


      # ------------------------------------------------------
      # 2. SET UP DOCKER BUILDX
      # ------------------------------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      # ------------------------------------------------------
      # 3. LOGIN TO DOCKER HUB
      # ------------------------------------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # ------------------------------------------------------
      # 4. BUILD FRONTEND LOCALLY
      # ------------------------------------------------------
      - name: Build frontend image locally
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile

          # Do not push before Trivy scanning.
          push: false

          # Load the image into the local Docker image store.
          load: true

          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/madhubani-frontend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/madhubani-frontend:latest

          cache-from: type=gha
          cache-to: type=gha,mode=max


      # ------------------------------------------------------
      # 5. BUILD BACKEND LOCALLY
      # ------------------------------------------------------
      - name: Build backend image locally
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          load: true

          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/madhubani-backend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/madhubani-backend:latest

          cache-from: type=gha
          cache-to: type=gha,mode=max


      # ------------------------------------------------------
      # 6. VERIFY IMAGES
      # ------------------------------------------------------
      - name: Verify locally built images
        run: |
          set -e

          echo "Images available on the runner:"
          docker image ls

          echo "Checking frontend image..."

          docker image inspect \
            "${{ secrets.DOCKERHUB_USERNAME }}/madhubani-frontend:${{ github.sha }}" \
            > /dev/null

          echo "Frontend image found."

          echo "Checking backend image..."

          docker image inspect \
            "${{ secrets.DOCKERHUB_USERNAME }}/madhubani-backend:${{ github.sha }}" \
            > /dev/null

          echo "Backend image found."


      # ------------------------------------------------------
      # 7. SCAN FRONTEND
      # ------------------------------------------------------
      - name: Scan frontend image with Trivy
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/madhubani-frontend:${{ github.sha }}
          scanners: vuln
          vuln-type: os,library
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          format: table
          exit-code: '0'


      # ------------------------------------------------------
      # 8. SCAN BACKEND
      # ------------------------------------------------------
      - name: Scan backend image with Trivy
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/madhubani-backend:${{ github.sha }}
          scanners: vuln
          vuln-type: os,library
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          format: table
          exit-code: '0'


      # ------------------------------------------------------
      # 9. PUSH FRONTEND
      # ------------------------------------------------------
      - name: Push frontend image to Docker Hub
        run: |
          set -e

          docker push \
            "${{ secrets.DOCKERHUB_USERNAME }}/madhubani-frontend:${{ github.sha }}"

          docker push \
            "${{ secrets.DOCKERHUB_USERNAME }}/madhubani-frontend:latest"


      # ------------------------------------------------------
      # 10. PUSH BACKEND
      # ------------------------------------------------------
      - name: Push backend image to Docker Hub
        run: |
          set -e

          docker push \
            "${{ secrets.DOCKERHUB_USERNAME }}/madhubani-backend:${{ github.sha }}"

          docker push \
            "${{ secrets.DOCKERHUB_USERNAME }}/madhubani-backend:latest"





































  # docker-build-and-push:
  #   name: Build and Push Docker Images
  #   runs-on: ubuntu-latest

  #   needs: owasp-dependency-check
  #     # - frontend-ci
  #     # - backend-ci
        

  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v4
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and push frontend image
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: ./frontend # ***
  #         file: ./frontend/Dockerfile # ***
  #         push: true
  #         tags: |
  #           ${{ secrets.DOCKERHUB_USERNAME }}/madhubani-frontend:${{ github.sha }}
  #           ${{ secrets.DOCKERHUB_USERNAME }}/madhubani-frontend:latest
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max

  #     - name: Build and push backend image
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: ./backend
  #         file: ./backend/Dockerfile
  #         push: true
  #         tags: |
  #           ${{ secrets.DOCKERHUB_USERNAME }}/madhubani-backend:${{ github.sha }}
  #           ${{ secrets.DOCKERHUB_USERNAME }}/madhubani-backend:latest
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max
  
  
  # # deploy:
  # #   runs-on: ubuntu-latest

  # #   steps:
  # #     - name: Checkout code
  # #       uses: actions/checkout@v4

  # #     - name: Deploy via SSH
  # #       uses: appleboy/ssh-action@v1.0.3
  # #       with:
  # #        host: ${{ secrets.SSH_HOST }}
  # #        username: ubuntu
  # #        key: ${{ secrets.SSH_KEY }}
  # #        script: |
  # #           cd /home/ubuntu/node
  # #           git pull origin main
  # #           npm install
  # #           npm run build
  # #           pm2 restart all